networks:
  docker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  ub_1:
    build: ./images/ubuntu_practice
    hostname: server
    cap_add:
      - NET_ADMIN
    networks:
      docker_network:
        ipv4_address: 192.168.100.10

  ub_2:
    build: ./images/ubuntu_practice
    hostname: client_one
    cap_add:
      - NET_ADMIN
    networks:
      docker_network:
        ipv4_address: 192.168.100.11

  ub_3:
    build: ./images/ubuntu_practice
    hostname: client_two
    cap_add:
      - NET_ADMIN
    networks:
      docker_network:
        ipv4_address: 192.168.100.12

  jump:
    build: ./images/jump_box
    ports:
      - "8001:22"
    hostname: jump
    cap_add:
      - NET_ADMIN
    networks:
      docker_network:
        ipv4_address: 192.168.100.100
